/* THE OFFICE FLOOR — the pre-AI workplace you can walk through.
   A reception, the open plan, a print room, the break room, a meeting
   room, the corner office, the server closet, the mailroom, a suggestion
   box, and the stationery cupboard. The Old Office off the Foyer is the
   same period seen through glass; this is the floor itself.
   Props and floors are read by the WorkAdventure converter; the raycaster
   ignores them. See CONTRIBUTING.md. */
ROOM("officefloor", {
  name: "The Office Floor",
  color: "#d9a05f",
  map: [
    "####A#######B#######C#####",
    "#........#.....#.........#",
    "M........J.....#.........K",
    "#........#.....#.........#",
    "####.#####.#######.#######",
    "#........................#",
    "####.##D######.#####.#####",
    "#............#...........E",
    "#............#...........#",
    "#............######.######",
    "#............#...........#",
    "#............#...........F",
    "#.##.####.#####.#####.####",
    "#....#.......#.....#.....#",
    "I....#.......#.....#.....#",
    "#....#.......#.....#.....#",
    "#########H#######G#####N##",
  ],
  floors: [
    "##########################",
    "#wwwwwwww#lllll#lllllllll#",
    "#wwwwwwww#lllll#lllllllll#",
    "#wwwwwwww#lllll#lllllllll#",
    "####l#####l#######l#######",
    "#llllllllllllllllllllllll#",
    "####c#########c#####c#####",
    "#cccccccccccc#ccccccccccc#",
    "#cccccccccccc#ccccccccccc#",
    "#cccccccccccc######w######",
    "#cccccccccccc#wwwwwwwwwww#",
    "#cccccccccccc#wwwwwwwwwww#",
    "#c##c####l#####k#####w####",
    "#wwww#lllllll#kkkkk#wwwww#",
    "#wwww#lllllll#kkkkk#wwwww#",
    "#wwww#lllllll#kkkkk#wwwww#",
    "##########################",
  ],
  floorKey: { w: "wood", c: "carpet", l: "lino", k: "concrete" },
  /* [x, y, what, variant] on floor cells; [x, y, what] in "wall" on wall cells facing the floor */
  props: [
    [2, 2, "reception"], [6, 2, "bench"], [7, 1, "plant"],
    [11, 1, "copier"], [13, 1, "copier"], [11, 3, "printer"], [13, 3, "shredder"], [14, 3, "boxes"],
    [17, 1, "cooler"], [18, 1, "coffee"], [23, 1, "microwave"], [24, 1, "fridge"], [20, 2, "breaktable"], [24, 3, "vending"],
    [2, 7, "desk", 0], [4, 7, "desk", 1], [6, 7, "desk", 2], [8, 7, "desk", 3], [10, 7, "desk", 4], [12, 7, "desk", 0],
    [2, 10, "desk", 1], [4, 10, "desk", 2], [6, 10, "desk", 3], [8, 10, "desk", 4], [10, 10, "desk", 0], [12, 10, "desk", 1],
    [1, 9, "partition"], [4, 9, "partition"], [7, 9, "partition"], [10, 9, "partition"], [12, 9, "printer"],
    [17, 7, "meetingtable"], [24, 8, "flipchart"], [22, 8, "chair"],
    [16, 10, "desk", 2], [23, 10, "bookshelf"], [24, 10, "bookshelf"], [24, 11, "plant"], [19, 11, "chair"],
    [16, 13, "rack"], [17, 13, "rack"], [18, 13, "rack"], [16, 15, "boxes"],
    [8, 14, "mailcart"], [12, 14, "boxes"], [7, 13, "boxes"],
    [2, 14, "bench"], [1, 15, "plant"],
    [21, 13, "shelves"], [24, 13, "shelves"], [22, 15, "boxes"]
  ],
  wall: [
    [7, 0, "bulletin"], [2, 0, "clock"], [16, 6, "whiteboard"], [21, 6, "screen"], [21, 9, "window"], [10, 12, "pigeonholes"], [6, 4, "clock"]
  ],
  exhibits: {
    A: { t: "The Sign-In Book", obj: "A visitors' book, ballpoint on a string. Last entry 4:12 pm.",
      body: ["Every visitor to the old office wrote their name in a book at the front desk, by hand, and was given a badge that said VISITOR in letters large enough to read across a room. The book knew who was in the building. Nobody ever read it, except once, after the fire drill.",
        "Reception was the building's face and its firewall. A person at a desk decided who came in, took messages on pink slips, and knew everyone's extension by heart. When the badge printer jammed, the organisation was, briefly, secure."] },
    M: { t: "The Punch Clock", obj: "A time clock, wall-mounted, with a rack of card stubs. It stamps 08:59.",
      body: ["Work was measured in presence. You arrived, you pushed a card into a machine that bit the time onto it, and the day officially existed. Leaving early was visible; arriving late was ink.",
        "Managers trusted the clock more than the work, because the clock was easy to read. The habit outlived the machine: the badge readers, the green dot in the chat app, the calendar that shows you as away. Presence was always the proxy. This clock just admitted it."] },
    B: { t: "The Print Room", obj: "A photocopier, mid-jam. The toner light is on. It has been on since 2009.",
      body: ["The print room was the loudest room and the most social one after the water cooler. Documents were made physical here so that they could be read, signed, lost, and made physical again. The machine had moods. Someone always knew the trick with the tray.",
        "Everything in this museum's placards would have been printed here first, forty copies, stapled top left, handed to people who would then ask for the file. The paperless office was announced in 1975. The print room never got the memo, because the memo was printed."] },
    J: { t: "The Fax Machine", obj: "A fax machine, beige, with a curl of thermal paper still in it.",
      body: ["The fax sent paper through a telephone. You fed a page in here and, with a sound like a modem clearing its throat, a copy came out somewhere else, faintly, slightly askew. For thirty years this was how contracts moved.",
        "It was replaced by email, then by scanning, then by nothing, since the documents stopped needing to exist. Some offices kept one because one client kept one. The last fax machine in any building is always for the last person who trusts it."] },
    C: { t: "The Break Room", obj: "A mug with a name on it. The name is not yours. Do not use the mug.",
      body: ["The break room held the fridge, the microwave, the kettle, the coffee machine, and a notice board of rules about the fridge. Here the organisation chart was suspended for eleven minutes at a time. People learned what was really happening in the building over reheated lunches.",
        "Anthropologists of the period note the mug: personal, labelled, fiercely defended. It marked territory in a shared space, the way a nameplate did on a door. The museum keeps it because the meetings that mattered happened next to the kettle, and nobody wrote them down."] },
    K: { t: "The Fridge Rules", obj: "A laminated notice, four bullet points, one of them underlined twice.",
      body: ["Every shared fridge produced a document. It began politely, asked people to label their food, and by the third revision had acquired capital letters and a deadline. Nobody signed it. Everybody knew who wrote it.",
        "It is the oldest governance problem in the building: a shared resource, no enforcement, and a notice instead of a mechanism. The museum hangs it in the Break Room rather than the Rotunda, but it belongs to both."] },
    D: { t: "The Inbox", obj: "A stacked pair of wire trays, IN and OUT. IN is fuller.",
      body: ["Before the inbox was a place on a screen it was a tray on a desk, and the work in it had weight. You could see how far behind a colleague was from across the room. Moving a page from IN to OUT was the entire theory of productivity.",
        "The tray taught a lesson the software forgot: a queue you can see is a queue you can refuse. When the tray was full, people said so. When the inbox is full, nobody can tell, least of all its owner."] },
    E: { t: "The Overhead Projector", obj: "An overhead projector and a stack of transparencies, one of them upside down.",
      body: ["Meetings were lit by a machine that shone light through sheets of plastic onto a wall. The presenter wrote on them with a pen, sometimes in real time, sometimes by accident on the glass. The fan was loud. The bulb was expensive. When it blew, the meeting ended and everyone was secretly relieved.",
        "The slide deck outlived the projector. Its habits, one idea per rectangle, bullet points, the chart that goes up, came from the transparency and the size of a wall. The old office invented the format that still runs most of the world's meetings, on a device that could set fire to itself."] },
    F: { t: "The Corner Office", obj: "A nameplate, brass, and a door that closed.",
      body: ["One room had two windows and a door, and in it sat the person who decided things. The corner office was the building's answer to the question of hierarchy: it was where the light was. People were promoted into it and, on occasion, carried out of it.",
        "The open plan abolished the office in name and kept it in practice: the corner became the glass box, then the calendar that nobody else could book. Every building tells you who matters by where they can close a door. This one just did it with a view."] },
    G: { t: "The Server Closet", obj: "One rack, humming. A sticky note on it says DO NOT TURN OFF.",
      body: ["Somewhere in every old office was a small hot room with a locked door, a single fan, and the machine that held everything: the files, the email, the one database. It hummed. It had a name. One person knew the password and was never allowed to be on holiday.",
        "The cloud moved the closet somewhere else and made it several thousand closets. What did not change is the sticky note. Every system that matters still has a machine somewhere that must not be turned off, and one person who knows why."] },
    H: { t: "The Pigeonholes", obj: "A wall of wooden slots, one per name. Two of them are still full.",
      body: ["The mailroom sorted the physical internet: letters, memos, catalogues, cheques, and the occasional cake, into a slot for each person. You checked your pigeonhole on the way in. It was the notification system, and it did not buzz.",
        "It also could not be muted, filtered, or searched, which is why the memo about the parking arrangement was found unopened in 2011 during the move. The museum keeps the wall as a monument to a simpler failure mode: the message arrived, and nobody looked."] },
    I: { t: "The Suggestion Box", obj: "A locked wooden box with a slot. The key was lost in 1998.",
      body: ["The suggestion box was the old office's feedback form: a slot, a stack of cards, and a promise that somebody read them. Suggestions were written in pencil, folded twice, and posted with the particular hope of a person who does not expect a reply.",
        "Open the box and you will find the whole culture: complaints about the coffee, a request for a second microwave, one carefully argued proposal for a four-day week, and a drawing. The museum leaves it locked. Some archives are better as a shape."] },
    N: { t: "The Stationery Cupboard", obj: "A cupboard, locked, containing the good pens.",
      body: ["Every office had one cupboard that held the paper clips, the staples, the envelopes, and the pens that actually wrote. Someone held the key. Requisitions were made. Whole friendships turned on access to the good stapler.",
        "It is easy to laugh at the cupboard until you notice what replaced it: a procurement portal with a three-day approval. The cupboard was the old office's supply chain, and its guardian was its first line of defence against entropy and, on Fridays, against the sales team."] }
  }
});
