#!/usr/bin/env node
/* Converts the museum's character grid and room modules into WorkAdventure
   maps, dressed as an exhibition: floors and wall faces tinted per hall, a
   kiosk for every exhibit with its title on the wall and the artifact under
   glass, a pool of light where the visitor stands, shadows along the walls,
   thresholds and plaques at hall doors, benches, plants, painted visitors,
   the Old Office behind glass, the gift shop, and the museum's name across
   the title wall. One map for the historic core, one per wing. */
"use strict";
const fs = require("fs"), path = require("path");
const load = require("./exhibits-index.cjs");
const { SIZE } = require("./paint.cjs");
const ROOT = path.join(__dirname, "..");
const M = load(ROOT);
const TS = require("./tileset.cjs")(M);
const S = 3, PX = S * SIZE;
function readEnv(k) { try { const m = fs.readFileSync(path.join(ROOT, ".env"), "utf8").match(new RegExp("^" + k + "=(.*)$", "m")); return m && m[1].trim(); } catch (e) { return null; } }
const BASE = (process.env.PLACARDS_BASE || readEnv("PLACARDS_BASE") || "https://world.aisafety.museum").replace(/\/$/, "");
const DIRS = [[0, 1], [0, -1], [1, 0], [-1, 0]];
const hash = s => { let h = 2166136261; for (const c of String(s)) { h ^= c.charCodeAt(0); h = Math.imul(h, 16777619); } return h >>> 0; };

const G = M.composed.MAP, GW = M.composed.MW, GH = M.composed.MH;
const cell = (x, y) => (x >= 0 && y >= 0 && x < GW && y < GH) ? G[y][x] : "#";
const isFloor = (x, y) => cell(x, y) === ".";
const rects = M.composed.ROOMRECTS;
function regionAt(x, y) {
  const ex = M.exhibits[cell(x, y)];
  if (ex && ex.wing !== "core" && rects.some(r => r.key === ex.wing)) return ex.wing;   /* an exhibit belongs to the room that declared it, even on a shared wall */
  for (const r of rects) if (x >= r.x0 && x <= r.x1 && y >= r.y0 && y <= r.y1) return r.key;
  return "core";
}
const regions = { core: { key: "core", name: "The Historic Core", bounds: { x0: 0, y0: 0, x1: M.coreW - 1, y1: M.coreH - 1 }, file: "core.tmj" } };
for (const r of rects) regions[r.key] = { key: r.key, name: M.ZONES[r.key].name, bounds: { x0: r.x0, y0: r.y0, x1: r.x1, y1: r.y1 }, file: r.key + ".tmj", def: M.rooms.find(d => d.key === r.key) };
const links = [], seenPair = new Set();
for (let y = 0; y < GH; y++) for (let x = 0; x < GW; x++) {
  if (!isFloor(x, y)) continue; const ra = regionAt(x, y);
  for (const [dx, dy] of [[1, 0], [0, 1]]) { const nx = x + dx, ny = y + dy; if (!isFloor(nx, ny)) continue; const rb = regionAt(nx, ny); if (ra === rb) continue; const key = [ra, rb].sort().join("|"); if (seenPair.has(key)) continue; seenPair.add(key); links.push({ a: { x, y, region: ra }, b: { x: nx, y: ny, region: rb } }); }
}
function facing(x, y) {
  for (const [dx, dy] of DIRS) if (isFloor(x + dx, y + dy)) return { dx, dy, fx: x + dx, fy: y + dy };
  for (const [dx, dy] of DIRS) if (cell(x + dx, y + dy) === "*" && isFloor(x + 2 * dx, y + 2 * dy)) return { dx, dy, fx: x + 2 * dx, fy: y + 2 * dy, glass: true };
  return null;
}
const gid = id => id + 1;
function prop(name, value) { const type = typeof value === "boolean" ? "bool" : typeof value === "number" ? (Number.isInteger(value) ? "int" : "float") : "string"; return { name, type, value }; }
function tileset() {
  return { columns: TS.cols, firstgid: 1, image: TS.file, imageheight: TS.height, imagewidth: TS.width, margin: 0, name: "museum", spacing: 0, tilecount: TS.tileCount, tileheight: SIZE, tilewidth: SIZE,
    tiles: [{ id: TS.T.COLLIDE, properties: [prop("collides", true)] }], properties: [prop("tilesetCopyright", "CC0. Generated by scripts/tileset.cjs for the Museum of AI Safety.")] };
}
const CORE_PROPS = [[2, 29, "desk", 0], [4, 29, "desk", 1], [2, 31, "desk", 2], [4, 31, "desk", 3], [3, 33, "desk", 4], [1, 28, "cabinet"], [6, 28, "boxes"], [6, 31, "cooler"], [1, 33, "copier"], [5, 30, "printer"], [6, 33, "coffee"], [2, 30, "partition"], [4, 30, "partition"], [6, 34, "plant"], [19, 37, "counter"], [23, 40, "totes"]];
const CORE_WALL = [[3, 27, "whiteboard"], [5, 27, "clock"]];
/* the furniture catalogue: sprite, offset in tiles inside the cell's 3 by 3 block, whether it blocks walking */
const O = TS.office, CAT = {
  desk: { grid: v => O.desks[(v || 0) % O.desks.length], dx: 0, dy: 0, collide: true },
  copier: { grid: O.copier, dx: 0, dy: 1, collide: true }, partition: { grid: O.partition, dx: 0, dy: 1, collide: false },
  bench: { grid: TS.bench, dx: 0, dy: 1, collide: true }, reception: { grid: O.reception, dx: 0, dy: 1, collide: true }, counter: { grid: TS.shop.counter, dx: 0, dy: 1, collide: true },
  shelves: { grid: TS.shop.shelf, dx: 0, dy: 1, collide: true }, vending: { grid: TS.shop.vending, dx: 0, dy: 1, collide: true },
  breaktable: { grid: O.breaktable, dx: 0, dy: 0, collide: true }, meetingtable: { grid: O.meetingtable, dx: 1, dy: 0, collide: true },
  printer: { id: O.printer }, cabinet: { id: O.cabinet }, cooler: { id: O.cooler }, coffee: { id: O.coffee }, boxes: { id: O.boxes }, fridge: { id: O.fridge }, microwave: { id: O.microwave },
  shredder: { id: O.shredder }, mailcart: { id: O.mailcart }, rack: { id: O.rack }, chair: { id: O.chair }, bookshelf: { id: O.bookshelf }, flipchart: { id: O.flipchart }, plant: { id: TS.plant }, totes: { id: TS.shop.totes },
  /* the street */
  lamppost: { grid: TS.street.lamppost, dx: 1, dy: 0, collide: "base" }, tree: { grid: TS.street.tree, dx: 1, dy: 0, collide: "base" },
  phonebox: { grid: TS.street.phonebox, dx: 1, dy: 0, collide: "base" }, busstop: { grid: TS.street.busstop, dx: 0, dy: 0, collide: "base" },
  car: { grid: TS.street.car, dx: 0, dy: 1, collide: true }, postbox: { id: TS.street.postbox }, bin: { id: TS.street.bin }, planter: { id: TS.street.planter },
  /* the waiting room */
  chairrow: { grid: TS.waiting.chairrow, dx: 0, dy: 1, collide: true }, ticketmachine: { id: TS.waiting.ticketmachine }, magtable: { id: TS.waiting.magtable },
  /* the memory wing */
  cardcat: { grid: TS.memory.cardcat, dx: 0, dy: 1, collide: true }, atlastable: { grid: TS.memory.atlastable, dx: 0, dy: 1, collide: true },
  globe: { id: TS.memory.globe }, phoneshelf: { id: TS.memory.phoneshelf },
  /* the verification desk */
  idbooth: { grid: TS.verify.idbooth, dx: 0, dy: 1, collide: true }, queuebarrier: { grid: TS.verify.queuebarrier, dx: 0, dy: 1, collide: true }, scanner: { id: TS.verify.scanner },
  /* the off switch gallery */
  bigbutton: { grid: TS.offswitch.bigbutton, dx: 0, dy: 1, collide: true }, caged: { id: TS.offswitch.caged }
};
const WALLCAT = { whiteboard: O.whiteboard, pigeonholes: O.pigeonholes, bulletin: O.bulletin, screen: O.screen, window: O.window, clock: O.clock,
  nowserving: TS.waiting.nowserving, switchbank: TS.offswitch.switchbank, cctv: TS.verify.cctv };

function buildMap(R) {
  const ox = R.bounds.x0 - 1, oy = R.bounds.y0 - 1, CW = R.bounds.x1 - R.bounds.x0 + 3, CH = R.bounds.y1 - R.bounds.y0 + 3, W = CW * S, H = CH * S;
  const layer = () => new Array(W * H).fill(0);
  const L = { floor: layer(), decor: layer(), props: layer(), walls: layer(), collisions: layer(), start: layer() }, zones = {};
  const set = (arr, tx, ty, id) => { if (tx >= 0 && ty >= 0 && tx < W && ty < H) arr[ty * W + tx] = gid(id); };
  const grid = (arr, g, tx, ty) => g.forEach((row, j) => row.forEach((id, i) => set(arr, tx + i, ty + j, id)));
  const tile = (cx, cy) => [(cx - ox) * S, (cy - oy) * S];
  const block = (arr, cx, cy, id) => { const [tx, ty] = tile(cx, cy); for (let j = 0; j < S; j++) for (let i = 0; i < S; i++) set(arr, tx + i, ty + j, id); };
  const myLinks = links.filter(l => l.a.region === R.key || l.b.region === R.key).map(l => l.a.region === R.key ? { mine: l.a, theirs: l.b } : { mine: l.b, theirs: l.a });
  const doorCells = new Set(myLinks.map(l => l.theirs.x + "," + l.theirs.y));
  const isDoor = (x, y) => doorCells.has(x + "," + y);
  const own = (x, y) => regionAt(x, y) === R.key;
  const walkable = (x, y) => (own(x, y) && isFloor(x, y)) || isDoor(x, y);
  const zoneOf = (x, y) => R.key === "core" ? M.zoneAt(x, y) : R.key;
  const objects = []; let oid = 1;
  const area = (name, cx, cy, props, w = 1, h = 1) => objects.push({ id: oid++, name, type: "area", x: (cx - ox) * PX, y: (cy - oy) * PX, width: w * PX, height: h * PX, rotation: 0, visible: true, properties: props });
  const facingCells = new Set(), exCells = {}, runs = {}, kiosksAt = [];
  let exhibitsHere = 0;

  /* ---------- pass one: every cell ---------- */
  for (let cy = R.bounds.y0 - 1; cy <= R.bounds.y1 + 1; cy++) for (let cx = R.bounds.x0 - 1; cx <= R.bounds.x1 + 1; cx++) {
    const [tx, ty] = tile(cx, cy), ch = cell(cx, cy);
    if (isDoor(cx, cy)) { block(L.floor, cx, cy, TS.T.DOOR); continue; }
    if (own(cx, cy) && ch === ".") {
      const z = zoneOf(cx, cy); let fl = TS.floors[z] || TS.floors.core;
      if (R.def && R.def.floors) { const row = R.def.floors[cy - R.bounds.y0] || "", st = R.def.floorKey[row[cx - R.bounds.x0]]; if (st && TS.floorStyles[st]) fl = TS.floorStyles[st]; }
      for (let j = 0; j < S; j++) for (let i = 0; i < S; i++) set(L.floor, tx + i, ty + j, fl[(tx + i + ty + j) % 2]);
      block(zones[z] = zones[z] || layer(), cx, cy, TS.T.ZONE);
      if (!walkable(cx, cy - 1)) grid(L.decor, TS.SHADOW.N, tx, ty);
      if (!walkable(cx, cy + 1)) grid(L.decor, TS.SHADOW.S, tx, ty + 2);
      if (!walkable(cx - 1, cy)) grid(L.decor, TS.SHADOW.W, tx, ty);
      if (!walkable(cx + 1, cy)) grid(L.decor, TS.SHADOW.E, tx + 2, ty);
      continue;
    }
    block(L.collisions, cx, cy, TS.T.COLLIDE);
    if (!own(cx, cy)) continue;
    let near = false;
    for (let j = -1; j <= 1 && !near; j++) for (let i = -1; i <= 1; i++) if (isFloor(cx + i, cy + j) || cell(cx + i, cy + j) === "*" || isDoor(cx + i, cy + j)) { near = true; break; }
    if (!near) continue;
    if (ch === "*") { block(L.walls, cx, cy, TS.T.GLASS); continue; }
    block(L.walls, cx, cy, TS.T.WALL_TOP);
    const f = facing(cx, cy), faceZone = f ? zoneOf(f.fx, f.fy) : zoneOf(cx, cy), face = TS.wallFaces[faceZone] || TS.wallFaces.core;
    if (isFloor(cx, cy + 1) || cell(cx, cy + 1) === "*") for (let i = 0; i < S; i++) set(L.walls, tx + i, ty + S - 1, face);
    const edgeRow = f ? (f.dy === 1 ? ty + S - 1 : f.dy === -1 ? ty : ty + 1) : ty + S - 1;
    const ex = M.exhibits[ch];
    if (ex && f) {
      const pillar = DIRS.every(([dx, dy]) => isFloor(cx + dx, cy + dy)), k = TS.kiosks[ch], mounted = ch === "g" || ch === "m";
      if (mounted) { for (let j = 0; j < S; j++) for (let i = 0; i < S; i++) set(L.walls, tx + i, ty + j, face); }   /* the live page hangs here */
      else grid(L.walls, pillar ? k.P : (f.dy === -1 ? k.N : k.S), tx, ty);
      (exCells[ch] = exCells[ch] || []).push({ x: f.fx, y: f.fy }); facingCells.add(f.fx + "," + f.fy);
      if (!pillar) { grid(L.decor, TS.LIGHT, ...tile(f.fx, f.fy)); kiosksAt.push({ ch, f }); }
      if (ch === "g" || ch === "m") { const key = ch + ":" + cy; (runs[key] = runs[key] || []).push(cx); }
    } else if (M.SHOP[ch] && f) {
      const p = M.SHOP[ch]; grid(L.walls, TS.shop.shelf, tx, edgeRow); facingCells.add(f.fx + "," + f.fy);
      area("shelf-" + M.kebab(p.name), f.fx, f.fy, p.url ? [prop("openTab", p.url), prop("openWebsiteTrigger", "onaction"), prop("openWebsiteTriggerMessage", "Press SPACE: " + p.name + " · " + p.aisle)]
        : [prop("openWebsite", BASE + "/placards/join.html"), prop("openWebsiteTrigger", "onaction"), prop("openWebsiteTriggerMessage", "Press SPACE: " + p.name), prop("openWebsiteWidth", 44)]);
    } else if (ch === "Y" && f) {
      grid(L.walls, TS.shop.vending, tx, edgeRow); facingCells.add(f.fx + "," + f.fy);
      area("vending-machine-" + cx, f.fx, f.fy, [prop("openWebsite", BASE + "/placards/join.html"), prop("openWebsiteTrigger", "onaction"), prop("openWebsiteTriggerMessage", "Press SPACE: GET INVOLVED · insert attention"), prop("openWebsiteWidth", 44)]);
    } else if (ch === "W") {
      const k = cx - 16; if (k >= 0 && k < 7) { const strip = [TS.banner[0].slice(3 * k, 3 * k + 3)]; grid(L.walls, strip, tx, ty + S - 1); grid(L.walls, strip, tx, ty); }
    }
  }
  for (const ch in exCells) {
    const ex = M.exhibits[ch], cs = exCells[ch];
    const x0 = Math.min(...cs.map(c => c.x)), x1 = Math.max(...cs.map(c => c.x)), y0 = Math.min(...cs.map(c => c.y)), y1 = Math.max(...cs.map(c => c.y));
    area(ex.slug, x0, y0, [prop("openWebsite", BASE + "/placards/" + ex.folder + "/" + ex.slug + ".html"), prop("openWebsiteTrigger", "onaction"), prop("openWebsiteTriggerMessage", "Press SPACE to read: " + ex.t),
      prop("openWebsiteWidth", 44), prop("openWebsiteAllowApi", true), prop("openWebsiteClosable", true), prop("exhibit", ex.n), prop("hall", ex.wing)], x1 - x0 + 1, y1 - y0 + 1);
    exhibitsHere++;
  }
  for (const k in runs) {
    const [ch, cyS] = k.split(":"), xs = runs[k].sort((a, b) => a - b), cy = +cyS;
    objects.push({ id: oid++, name: ch === "g" ? "departures-board" : "march-of-progress", type: "", x: (xs[0] - ox) * PX, y: (cy - oy) * PX, width: xs.length * PX, height: PX, rotation: 0, visible: true, properties: [prop("url", BASE + "/placards/" + (ch === "g" ? "board" : "mural") + ".html"), prop("allowApi", false)] });
  }
  for (const l of myLinks) {
    const other = regions[l.theirs.region];
    area("to-" + other.key, l.theirs.x, l.theirs.y, [prop("exitUrl", other.file + "#from-" + R.key)]);
    area("from-" + other.key, l.mine.x, l.mine.y, [prop("start", true)]);
    if (R.key !== "core") block(L.start, l.mine.x, l.mine.y, TS.T.START);
  }
  if (R.key === "core") { block(L.start, 19, 33, TS.T.START); area("old-office-viewing-gallery", 8, 28, [prop("silent", true)], 5, 7); }

  /* signage: at every door, a board naming what is through it, and one naming where you have arrived */
  const signedCells = new Set();
  function signAt(near, awayFrom, zoneKey) {
    const board = TS.bigSigns[zoneKey]; if (!board) return;
    const dx = Math.sign(near.x - awayFrom.x), dy = Math.sign(near.y - awayFrom.y);
    const perp = dx ? [[0, 1], [0, -1]] : [[1, 0], [-1, 0]];
    for (const [px2, py2] of perp) for (const step of [0, 1]) {
      const wx = near.x + px2 + dx * step, wy = near.y + py2 + dy * step;
      if (!own(wx, wy) || cell(wx, wy) !== "#" || signedCells.has(wx + "," + wy)) continue;
      let touches = false;
      for (const [ax, ay] of DIRS) if (walkable(wx + ax, wy + ay)) touches = true;
      if (!touches) continue;
      const [tx, ty] = tile(wx, wy);
      grid(L.walls, board, tx, ty + 1);
      signedCells.add(wx + "," + wy);
      return;
    }
  }
  for (const l of myLinks) {
    signAt(l.mine, l.theirs, l.theirs.region === "core" ? "foyer" : l.theirs.region);   /* where this door goes */
    if (R.key !== "core") signAt(l.mine, l.theirs, R.key);                              /* and where you now are */
  }
  if (R.key === "core") {
    let best = null;
    for (let cy = 28; cy <= 36; cy++) for (let cx = 12; cx <= 27; cx++) {
      if (!own(cx, cy) || cell(cx, cy) !== "#" || signedCells.has(cx + "," + cy)) continue;
      if (!DIRS.some(([ax, ay]) => walkable(cx + ax, cy + ay))) continue;
      const d = Math.hypot(cx - 19, cy - 33);
      if (!best || d < best.d) best = { cx, cy, d };
    }
    if (best) {
      const [tx, ty] = tile(best.cx, best.cy);
      grid(L.walls, TS.directoryBoard, tx, ty + 1);
      signedCells.add(best.cx + "," + best.cy);
      const f = DIRS.map(([ax, ay]) => [best.cx + ax, best.cy + ay]).find(([ax, ay]) => walkable(ax, ay));
      if (f) area("museum-directory", f[0], f[1], [prop("openWebsite", BASE + "/placards/index.html"), prop("openWebsiteTrigger", "onaction"),
        prop("openWebsiteTriggerMessage", "Press SPACE for the museum directory"), prop("openWebsiteWidth", 44), prop("openWebsiteAllowApi", true)]);
    }
  }

  /* ---------- furniture: the core's own, or the room module's ---------- */
  const propCells = new Set();
  const PROPS = R.key === "core" ? CORE_PROPS : (R.def ? R.def.props.map(([x, y, w, v]) => [x + R.bounds.x0, y + R.bounds.y0, w, v]) : []);
  const WALLS = R.key === "core" ? CORE_WALL : (R.def ? R.def.wall.map(([x, y, w]) => [x + R.bounds.x0, y + R.bounds.y0, w]) : []);
  for (const [cx, cy, what, v] of PROPS) {
    const c = CAT[what]; if (!c) { console.warn("unknown prop", what); continue; }
    const [tx, ty] = tile(cx, cy); propCells.add(cx + "," + cy);
    if (c.id !== undefined) { set(L.props, tx + 1, ty + 1, c.id); if (c.collide !== false) set(L.collisions, tx + 1, ty + 1, TS.T.COLLIDE); continue; }
    const g = typeof c.grid === "function" ? c.grid(v) : c.grid;
    grid(L.props, g, tx + c.dx, ty + c.dy);
    if (c.collide) g.forEach((row, j) => row.forEach((_, i) => { if (c.collide !== "base" || j === g.length - 1) set(L.collisions, tx + c.dx + i, ty + c.dy + j, TS.T.COLLIDE); }));
    if (g[0].length > 3) propCells.add((cx + 1) + "," + cy);
  }
  for (const [cx, cy, what] of WALLS) {
    const w = WALLCAT[what]; if (w === undefined) { console.warn("unknown wall prop", what); continue; }
    const [tx, ty] = tile(cx, cy);
    if (Array.isArray(w)) grid(L.walls, w, tx, ty + 2); else set(L.walls, tx + 1, ty + 2, w);
  }

  /* ---------- pass two: dressing per hall ---------- */
  const floorCells = [];
  for (let cy = R.bounds.y0; cy <= R.bounds.y1; cy++) for (let cx = R.bounds.x0; cx <= R.bounds.x1; cx++) if (own(cx, cy) && isFloor(cx, cy)) floorCells.push([cx, cy]);
  const byZone = {}; for (const c of floorCells) (byZone[zoneOf(c[0], c[1])] = byZone[zoneOf(c[0], c[1])] || []).push(c);
  const thresholdCells = new Set(), hallSign = {};
  for (const [cx, cy] of floorCells) for (const [dx, dy] of DIRS) {
    const nx = cx + dx, ny = cy + dy; if (!walkable(nx, ny) || !own(nx, ny)) continue;
    const za = zoneOf(cx, cy), zb = zoneOf(nx, ny); if (za === zb) continue;
    const [tx, ty] = tile(cx, cy), dir = dy === -1 ? "N" : dy === 1 ? "S" : dx === -1 ? "W" : "E";
    if (za > zb) grid(L.decor, TS.THRESH[dir], dir === "S" ? tx : dir === "E" ? tx + 2 : tx, dir === "S" ? ty + 2 : dir === "E" ? ty : ty);
    thresholdCells.add(cx + "," + cy);
    if (!hallSign[za]) { const perp = dy !== 0 ? [[1, 0], [-1, 0]] : [[0, 1], [0, -1]]; for (const [px2, py2] of perp) { const wx = cx + px2, wy = cy + py2; if (own(wx, wy) && cell(wx, wy) === "#") { hallSign[za] = [wx, wy]; break; } } }
  }
  for (const z in hallSign) if (TS.signs[z]) { const [tx, ty] = tile(...hallSign[z]); grid(L.walls, TS.signs[z], tx, ty + 1); }
  const busy = new Set([...facingCells, ...thresholdCells, ...doorCells, ...propCells, ...signedCells]);
  const furnished = PROPS.length > 0 && R.key !== "core";
  for (const l of myLinks) for (const [dx, dy] of DIRS) busy.add((l.mine.x + dx) + "," + (l.mine.y + dy));
  const allAround = (cx, cy) => { for (let j = -1; j <= 1; j++) for (let i = -1; i <= 1; i++) if (!walkable(cx + i, cy + j)) return false; return true; };
  for (const z in byZone) {
    const cells = byZone[z]; if (z === "office") continue;
    for (const [cx, cy] of cells) if (allAround(cx, cy) && !busy.has(cx + "," + cy) && (cx * 3 + cy * 7) % 6 === 0) grid(L.decor, TS.LIGHT_SOFT, ...tile(cx, cy));
    const cxm = cells.reduce((a, c) => a + c[0], 0) / cells.length, cym = cells.reduce((a, c) => a + c[1], 0) / cells.length;
    const want = furnished ? 0 : cells.length >= 60 ? 2 : cells.length >= 18 ? 1 : 0, placed = [];
    const cands = cells.filter(([x, y]) => allAround(x, y) && !busy.has(x + "," + y)).sort((a, b) => Math.hypot(a[0] - cxm, a[1] - cym) - Math.hypot(b[0] - cxm, b[1] - cym));
    for (const [x, y] of cands) { if (placed.length >= want) break; if (placed.some(p => Math.hypot(p[0] - x, p[1] - y) < 4)) continue; const [tx, ty] = tile(x, y); grid(L.props, TS.bench, tx, ty + 1); for (let i = 0; i < 3; i++) set(L.collisions, tx + i, ty + 1, TS.T.COLLIDE); placed.push([x, y]); busy.add(x + "," + y); }
    let plants = 0;
    for (const [x, y] of cells) {
      if (plants >= (furnished ? 0 : 6) || busy.has(x + "," + y)) continue;
      const n = !walkable(x, y - 1), s2 = !walkable(x, y + 1), w = !walkable(x - 1, y), e = !walkable(x + 1, y);
      const corner = n && w ? [0, 0] : n && e ? [2, 0] : s2 && w ? [0, 2] : s2 && e ? [2, 2] : null; if (!corner) continue;
      const [tx, ty] = tile(x, y); set(L.props, tx + corner[0], ty + corner[1], TS.plant); set(L.collisions, tx + corner[0], ty + corner[1], TS.T.COLLIDE); plants++;
    }
  }
  for (const { ch, f } of kiosksAt) {
    const h = hash(R.key + ch); if (h % 3) continue;
    const [tx, ty] = tile(f.fx, f.fy), col = (h >> 3) % 2 ? 0 : 2;
    if (f.dy === 1) grid(L.props, TS.visitors[h % TS.visitors.length], tx + col, ty);
    else if (f.dy === -1) grid(L.props, TS.visitorsFront[h % TS.visitorsFront.length], tx + col, ty + 1);
  }
  let lid = 1;
  const tl = (name, data) => ({ id: lid++, name, type: "tilelayer", visible: true, opacity: 1, x: 0, y: 0, width: W, height: H, data });
  const layers = [tl("floor", L.floor), tl("decor", L.decor), tl("props", L.props), tl("walls", L.walls), tl("collisions", L.collisions)];
  for (const z of Object.keys(zones).sort()) layers.push(tl("zone-" + z, zones[z]));
  layers.push(tl("start", L.start));
  layers.push({ id: lid++, name: "floorLayer", type: "objectgroup", draworder: "topdown", visible: true, opacity: 1, x: 0, y: 0, objects });
  const map = { compressionlevel: -1, height: H, width: W, infinite: false, layers, nextlayerid: lid, nextobjectid: oid, orientation: "orthogonal", renderorder: "right-down", tiledversion: "1.11.2", tileheight: SIZE, tilewidth: SIZE, type: "map", version: "1.10",
    properties: [prop("mapName", "The Museum of AI Safety · " + R.name), prop("mapDescription", "A walkable museum of AI safety. Press SPACE at a placard to read it."), prop("mapCopyright", "Maps and placards CC BY 4.0 The Museum of AI Safety. Tileset CC0."), prop("script", "../src/main.ts")], tilesets: [tileset()] };
  return { map, W, H, exhibitsHere, exits: myLinks.map(l => l.theirs.region), objects: objects.length, zones: Object.keys(zones) };
}

fs.mkdirSync(path.join(ROOT, "maps"), { recursive: true });
const summary = [];
for (const key of Object.keys(regions)) { const R = regions[key], out = buildMap(R); fs.writeFileSync(path.join(ROOT, "maps", R.file), JSON.stringify(out.map)); summary.push({ file: R.file, tiles: out.W + "x" + out.H, exhibits: out.exhibitsHere, exits: out.exits.join(","), objects: out.objects }); }
const halls = {}; for (const k in M.ZONES) halls[k] = M.ZONES[k].name;
fs.mkdirSync(path.join(ROOT, "src"), { recursive: true }); fs.writeFileSync(path.join(ROOT, "src", "halls.json"), JSON.stringify(halls, null, 2));
console.table(summary);
console.log("exhibit areas total:", summary.reduce((a, s) => a + s.exhibits, 0), "of", M.total, "· tiles in set:", TS.tileCount, "· placards base:", BASE);
